version: '2'

services:

    db:
        image: mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=root"
        volumes:
            - "$HOME/.sql:/var/lib/mysql"
    php:
        build: "./php"
        ports:
            - "8080:80"
        volumes:
            - "$HOME/DAMP/http:/var/www/html"
    pma:
        image: phpmyadmin/phpmyadmin
        environment:
            - "PMA_HOST=db"
        ports:
            - "8081:80"
